//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointsFacultyView.PointsWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentPoints", Namespace="http://pointservice.org/")]
    [System.SerializableAttribute()]
    public partial class StudentPoints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNumberField;
        
        private double PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentNumber {
            get {
                return this.StudentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNumberField, value) != true)) {
                    this.StudentNumberField = value;
                    this.RaisePropertyChanged("StudentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pointservice.org/", ConfigurationName="PointsWebService.PointsServiceSoap")]
    public interface PointsServiceSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/Login", ReplyAction="*")]
        PointsFacultyView.PointsWebService.LoginResponse Login(PointsFacultyView.PointsWebService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.LoginResponse> LoginAsync(PointsFacultyView.PointsWebService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name number from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetStudentPoints", ReplyAction="*")]
        PointsFacultyView.PointsWebService.GetStudentPointsResponse GetStudentPoints(PointsFacultyView.PointsWebService.GetStudentPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetStudentPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetStudentPointsResponse> GetStudentPointsAsync(PointsFacultyView.PointsWebService.GetStudentPointsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllStudentPointsResult from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetAllStudentPoints", ReplyAction="*")]
        PointsFacultyView.PointsWebService.GetAllStudentPointsResponse GetAllStudentPoints(PointsFacultyView.PointsWebService.GetAllStudentPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetAllStudentPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetAllStudentPointsResponse> GetAllStudentPointsAsync(PointsFacultyView.PointsWebService.GetAllStudentPointsRequest request);
        
        // CODEGEN: Generating message contract since element name userRole from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/UsePoints", ReplyAction="*")]
        PointsFacultyView.PointsWebService.UsePointsResponse UsePoints(PointsFacultyView.PointsWebService.UsePointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/UsePoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.UsePointsResponse> UsePointsAsync(PointsFacultyView.PointsWebService.UsePointsRequest request);
        
        // CODEGEN: Generating message contract since element name userRole from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/AddPoints", ReplyAction="*")]
        PointsFacultyView.PointsWebService.AddPointsResponse AddPoints(PointsFacultyView.PointsWebService.AddPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/AddPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.AddPointsResponse> AddPointsAsync(PointsFacultyView.PointsWebService.AddPointsRequest request);
        
        // CODEGEN: Generating message contract since element name studentNumber from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/IfStudentExists", ReplyAction="*")]
        PointsFacultyView.PointsWebService.IfStudentExistsResponse IfStudentExists(PointsFacultyView.PointsWebService.IfStudentExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/IfStudentExists", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.IfStudentExistsResponse> IfStudentExistsAsync(PointsFacultyView.PointsWebService.IfStudentExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(PointsFacultyView.PointsWebService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emailAddress;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userId, string emailAddress) {
            this.userId = userId;
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(PointsFacultyView.PointsWebService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.GetStudentPointsRequestBody Body;
        
        public GetStudentPointsRequest() {
        }
        
        public GetStudentPointsRequest(PointsFacultyView.PointsWebService.GetStudentPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetStudentPointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        public GetStudentPointsRequestBody() {
        }
        
        public GetStudentPointsRequestBody(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.GetStudentPointsResponseBody Body;
        
        public GetStudentPointsResponse() {
        }
        
        public GetStudentPointsResponse(PointsFacultyView.PointsWebService.GetStudentPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetStudentPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PointsFacultyView.PointsWebService.StudentPoints GetStudentPointsResult;
        
        public GetStudentPointsResponseBody() {
        }
        
        public GetStudentPointsResponseBody(PointsFacultyView.PointsWebService.StudentPoints GetStudentPointsResult) {
            this.GetStudentPointsResult = GetStudentPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.GetAllStudentPointsRequestBody Body;
        
        public GetAllStudentPointsRequest() {
        }
        
        public GetAllStudentPointsRequest(PointsFacultyView.PointsWebService.GetAllStudentPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStudentPointsRequestBody {
        
        public GetAllStudentPointsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.GetAllStudentPointsResponseBody Body;
        
        public GetAllStudentPointsResponse() {
        }
        
        public GetAllStudentPointsResponse(PointsFacultyView.PointsWebService.GetAllStudentPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetAllStudentPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PointsFacultyView.PointsWebService.StudentPoints[] GetAllStudentPointsResult;
        
        public GetAllStudentPointsResponseBody() {
        }
        
        public GetAllStudentPointsResponseBody(PointsFacultyView.PointsWebService.StudentPoints[] GetAllStudentPointsResult) {
            this.GetAllStudentPointsResult = GetAllStudentPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsePointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsePoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.UsePointsRequestBody Body;
        
        public UsePointsRequest() {
        }
        
        public UsePointsRequest(PointsFacultyView.PointsWebService.UsePointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class UsePointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string studentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double points;
        
        public UsePointsRequestBody() {
        }
        
        public UsePointsRequestBody(string userRole, string studentNumber, double points) {
            this.userRole = userRole;
            this.studentNumber = studentNumber;
            this.points = points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsePointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsePointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.UsePointsResponseBody Body;
        
        public UsePointsResponse() {
        }
        
        public UsePointsResponse(PointsFacultyView.PointsWebService.UsePointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class UsePointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UsePointsResult;
        
        public UsePointsResponseBody() {
        }
        
        public UsePointsResponseBody(bool UsePointsResult) {
            this.UsePointsResult = UsePointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.AddPointsRequestBody Body;
        
        public AddPointsRequest() {
        }
        
        public AddPointsRequest(PointsFacultyView.PointsWebService.AddPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class AddPointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string studentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double points;
        
        public AddPointsRequestBody() {
        }
        
        public AddPointsRequestBody(string userRole, string studentNumber, double points) {
            this.userRole = userRole;
            this.studentNumber = studentNumber;
            this.points = points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.AddPointsResponseBody Body;
        
        public AddPointsResponse() {
        }
        
        public AddPointsResponse(PointsFacultyView.PointsWebService.AddPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class AddPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPointsResult;
        
        public AddPointsResponseBody() {
        }
        
        public AddPointsResponseBody(bool AddPointsResult) {
            this.AddPointsResult = AddPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IfStudentExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IfStudentExists", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.IfStudentExistsRequestBody Body;
        
        public IfStudentExistsRequest() {
        }
        
        public IfStudentExistsRequest(PointsFacultyView.PointsWebService.IfStudentExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class IfStudentExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentNumber;
        
        public IfStudentExistsRequestBody() {
        }
        
        public IfStudentExistsRequestBody(string studentNumber) {
            this.studentNumber = studentNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IfStudentExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IfStudentExistsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsFacultyView.PointsWebService.IfStudentExistsResponseBody Body;
        
        public IfStudentExistsResponse() {
        }
        
        public IfStudentExistsResponse(PointsFacultyView.PointsWebService.IfStudentExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class IfStudentExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IfStudentExistsResult;
        
        public IfStudentExistsResponseBody() {
        }
        
        public IfStudentExistsResponseBody(bool IfStudentExistsResult) {
            this.IfStudentExistsResult = IfStudentExistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PointsServiceSoapChannel : PointsFacultyView.PointsWebService.PointsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PointsServiceSoapClient : System.ServiceModel.ClientBase<PointsFacultyView.PointsWebService.PointsServiceSoap>, PointsFacultyView.PointsWebService.PointsServiceSoap {
        
        public PointsServiceSoapClient() {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PointsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.LoginResponse PointsFacultyView.PointsWebService.PointsServiceSoap.Login(PointsFacultyView.PointsWebService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userId, string emailAddress) {
            PointsFacultyView.PointsWebService.LoginRequest inValue = new PointsFacultyView.PointsWebService.LoginRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.emailAddress = emailAddress;
            PointsFacultyView.PointsWebService.LoginResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.LoginResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.LoginAsync(PointsFacultyView.PointsWebService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.LoginResponse> LoginAsync(string userId, string emailAddress) {
            PointsFacultyView.PointsWebService.LoginRequest inValue = new PointsFacultyView.PointsWebService.LoginRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.emailAddress = emailAddress;
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.GetStudentPointsResponse PointsFacultyView.PointsWebService.PointsServiceSoap.GetStudentPoints(PointsFacultyView.PointsWebService.GetStudentPointsRequest request) {
            return base.Channel.GetStudentPoints(request);
        }
        
        public PointsFacultyView.PointsWebService.StudentPoints GetStudentPoints(string number) {
            PointsFacultyView.PointsWebService.GetStudentPointsRequest inValue = new PointsFacultyView.PointsWebService.GetStudentPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.GetStudentPointsRequestBody();
            inValue.Body.number = number;
            PointsFacultyView.PointsWebService.GetStudentPointsResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).GetStudentPoints(inValue);
            return retVal.Body.GetStudentPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetStudentPointsResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.GetStudentPointsAsync(PointsFacultyView.PointsWebService.GetStudentPointsRequest request) {
            return base.Channel.GetStudentPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetStudentPointsResponse> GetStudentPointsAsync(string number) {
            PointsFacultyView.PointsWebService.GetStudentPointsRequest inValue = new PointsFacultyView.PointsWebService.GetStudentPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.GetStudentPointsRequestBody();
            inValue.Body.number = number;
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).GetStudentPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.GetAllStudentPointsResponse PointsFacultyView.PointsWebService.PointsServiceSoap.GetAllStudentPoints(PointsFacultyView.PointsWebService.GetAllStudentPointsRequest request) {
            return base.Channel.GetAllStudentPoints(request);
        }
        
        public PointsFacultyView.PointsWebService.StudentPoints[] GetAllStudentPoints() {
            PointsFacultyView.PointsWebService.GetAllStudentPointsRequest inValue = new PointsFacultyView.PointsWebService.GetAllStudentPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.GetAllStudentPointsRequestBody();
            PointsFacultyView.PointsWebService.GetAllStudentPointsResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).GetAllStudentPoints(inValue);
            return retVal.Body.GetAllStudentPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetAllStudentPointsResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.GetAllStudentPointsAsync(PointsFacultyView.PointsWebService.GetAllStudentPointsRequest request) {
            return base.Channel.GetAllStudentPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.GetAllStudentPointsResponse> GetAllStudentPointsAsync() {
            PointsFacultyView.PointsWebService.GetAllStudentPointsRequest inValue = new PointsFacultyView.PointsWebService.GetAllStudentPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.GetAllStudentPointsRequestBody();
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).GetAllStudentPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.UsePointsResponse PointsFacultyView.PointsWebService.PointsServiceSoap.UsePoints(PointsFacultyView.PointsWebService.UsePointsRequest request) {
            return base.Channel.UsePoints(request);
        }
        
        public bool UsePoints(string userRole, string studentNumber, double points) {
            PointsFacultyView.PointsWebService.UsePointsRequest inValue = new PointsFacultyView.PointsWebService.UsePointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.UsePointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            PointsFacultyView.PointsWebService.UsePointsResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).UsePoints(inValue);
            return retVal.Body.UsePointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.UsePointsResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.UsePointsAsync(PointsFacultyView.PointsWebService.UsePointsRequest request) {
            return base.Channel.UsePointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.UsePointsResponse> UsePointsAsync(string userRole, string studentNumber, double points) {
            PointsFacultyView.PointsWebService.UsePointsRequest inValue = new PointsFacultyView.PointsWebService.UsePointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.UsePointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).UsePointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.AddPointsResponse PointsFacultyView.PointsWebService.PointsServiceSoap.AddPoints(PointsFacultyView.PointsWebService.AddPointsRequest request) {
            return base.Channel.AddPoints(request);
        }
        
        public bool AddPoints(string userRole, string studentNumber, double points) {
            PointsFacultyView.PointsWebService.AddPointsRequest inValue = new PointsFacultyView.PointsWebService.AddPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.AddPointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            PointsFacultyView.PointsWebService.AddPointsResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).AddPoints(inValue);
            return retVal.Body.AddPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.AddPointsResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.AddPointsAsync(PointsFacultyView.PointsWebService.AddPointsRequest request) {
            return base.Channel.AddPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.AddPointsResponse> AddPointsAsync(string userRole, string studentNumber, double points) {
            PointsFacultyView.PointsWebService.AddPointsRequest inValue = new PointsFacultyView.PointsWebService.AddPointsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.AddPointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).AddPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsFacultyView.PointsWebService.IfStudentExistsResponse PointsFacultyView.PointsWebService.PointsServiceSoap.IfStudentExists(PointsFacultyView.PointsWebService.IfStudentExistsRequest request) {
            return base.Channel.IfStudentExists(request);
        }
        
        public bool IfStudentExists(string studentNumber) {
            PointsFacultyView.PointsWebService.IfStudentExistsRequest inValue = new PointsFacultyView.PointsWebService.IfStudentExistsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.IfStudentExistsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            PointsFacultyView.PointsWebService.IfStudentExistsResponse retVal = ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).IfStudentExists(inValue);
            return retVal.Body.IfStudentExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.IfStudentExistsResponse> PointsFacultyView.PointsWebService.PointsServiceSoap.IfStudentExistsAsync(PointsFacultyView.PointsWebService.IfStudentExistsRequest request) {
            return base.Channel.IfStudentExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsFacultyView.PointsWebService.IfStudentExistsResponse> IfStudentExistsAsync(string studentNumber) {
            PointsFacultyView.PointsWebService.IfStudentExistsRequest inValue = new PointsFacultyView.PointsWebService.IfStudentExistsRequest();
            inValue.Body = new PointsFacultyView.PointsWebService.IfStudentExistsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            return ((PointsFacultyView.PointsWebService.PointsServiceSoap)(this)).IfStudentExistsAsync(inValue);
        }
    }
}
