//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointsStudentView.PointsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentPoints", Namespace="http://pointservice.org/")]
    [System.SerializableAttribute()]
    public partial class StudentPoints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentNumberField;
        
        private double PointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StudentNumber {
            get {
                return this.StudentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentNumberField, value) != true)) {
                    this.StudentNumberField = value;
                    this.RaisePropertyChanged("StudentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pointservice.org/", ConfigurationName="PointsService.PointsServiceSoap")]
    public interface PointsServiceSoap {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/Login", ReplyAction="*")]
        PointsStudentView.PointsService.LoginResponse Login(PointsStudentView.PointsService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.LoginResponse> LoginAsync(PointsStudentView.PointsService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name number from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetStudentPoints", ReplyAction="*")]
        PointsStudentView.PointsService.GetStudentPointsResponse GetStudentPoints(PointsStudentView.PointsService.GetStudentPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetStudentPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.GetStudentPointsResponse> GetStudentPointsAsync(PointsStudentView.PointsService.GetStudentPointsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllStudentPointsResult from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetAllStudentPoints", ReplyAction="*")]
        PointsStudentView.PointsService.GetAllStudentPointsResponse GetAllStudentPoints(PointsStudentView.PointsService.GetAllStudentPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/GetAllStudentPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.GetAllStudentPointsResponse> GetAllStudentPointsAsync(PointsStudentView.PointsService.GetAllStudentPointsRequest request);
        
        // CODEGEN: Generating message contract since element name userRole from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/UsePoints", ReplyAction="*")]
        PointsStudentView.PointsService.UsePointsResponse UsePoints(PointsStudentView.PointsService.UsePointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/UsePoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.UsePointsResponse> UsePointsAsync(PointsStudentView.PointsService.UsePointsRequest request);
        
        // CODEGEN: Generating message contract since element name userRole from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/AddPoints", ReplyAction="*")]
        PointsStudentView.PointsService.AddPointsResponse AddPoints(PointsStudentView.PointsService.AddPointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/AddPoints", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.AddPointsResponse> AddPointsAsync(PointsStudentView.PointsService.AddPointsRequest request);
        
        // CODEGEN: Generating message contract since element name studentNumber from namespace http://pointservice.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/IfStudentExists", ReplyAction="*")]
        PointsStudentView.PointsService.IfStudentExistsResponse IfStudentExists(PointsStudentView.PointsService.IfStudentExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pointservice.org/IfStudentExists", ReplyAction="*")]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.IfStudentExistsResponse> IfStudentExistsAsync(PointsStudentView.PointsService.IfStudentExistsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(PointsStudentView.PointsService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string emailAddress;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string userId, string emailAddress) {
            this.userId = userId;
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(PointsStudentView.PointsService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.GetStudentPointsRequestBody Body;
        
        public GetStudentPointsRequest() {
        }
        
        public GetStudentPointsRequest(PointsStudentView.PointsService.GetStudentPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetStudentPointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        public GetStudentPointsRequestBody() {
        }
        
        public GetStudentPointsRequestBody(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.GetStudentPointsResponseBody Body;
        
        public GetStudentPointsResponse() {
        }
        
        public GetStudentPointsResponse(PointsStudentView.PointsService.GetStudentPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetStudentPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PointsStudentView.PointsService.StudentPoints GetStudentPointsResult;
        
        public GetStudentPointsResponseBody() {
        }
        
        public GetStudentPointsResponseBody(PointsStudentView.PointsService.StudentPoints GetStudentPointsResult) {
            this.GetStudentPointsResult = GetStudentPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.GetAllStudentPointsRequestBody Body;
        
        public GetAllStudentPointsRequest() {
        }
        
        public GetAllStudentPointsRequest(PointsStudentView.PointsService.GetAllStudentPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllStudentPointsRequestBody {
        
        public GetAllStudentPointsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllStudentPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllStudentPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.GetAllStudentPointsResponseBody Body;
        
        public GetAllStudentPointsResponse() {
        }
        
        public GetAllStudentPointsResponse(PointsStudentView.PointsService.GetAllStudentPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class GetAllStudentPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PointsStudentView.PointsService.StudentPoints[] GetAllStudentPointsResult;
        
        public GetAllStudentPointsResponseBody() {
        }
        
        public GetAllStudentPointsResponseBody(PointsStudentView.PointsService.StudentPoints[] GetAllStudentPointsResult) {
            this.GetAllStudentPointsResult = GetAllStudentPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsePointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsePoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.UsePointsRequestBody Body;
        
        public UsePointsRequest() {
        }
        
        public UsePointsRequest(PointsStudentView.PointsService.UsePointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class UsePointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string studentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double points;
        
        public UsePointsRequestBody() {
        }
        
        public UsePointsRequestBody(string userRole, string studentNumber, double points) {
            this.userRole = userRole;
            this.studentNumber = studentNumber;
            this.points = points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsePointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsePointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.UsePointsResponseBody Body;
        
        public UsePointsResponse() {
        }
        
        public UsePointsResponse(PointsStudentView.PointsService.UsePointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class UsePointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UsePointsResult;
        
        public UsePointsResponseBody() {
        }
        
        public UsePointsResponseBody(bool UsePointsResult) {
            this.UsePointsResult = UsePointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPoints", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.AddPointsRequestBody Body;
        
        public AddPointsRequest() {
        }
        
        public AddPointsRequest(PointsStudentView.PointsService.AddPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class AddPointsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userRole;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string studentNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double points;
        
        public AddPointsRequestBody() {
        }
        
        public AddPointsRequestBody(string userRole, string studentNumber, double points) {
            this.userRole = userRole;
            this.studentNumber = studentNumber;
            this.points = points;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPointsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.AddPointsResponseBody Body;
        
        public AddPointsResponse() {
        }
        
        public AddPointsResponse(PointsStudentView.PointsService.AddPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class AddPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPointsResult;
        
        public AddPointsResponseBody() {
        }
        
        public AddPointsResponseBody(bool AddPointsResult) {
            this.AddPointsResult = AddPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IfStudentExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IfStudentExists", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.IfStudentExistsRequestBody Body;
        
        public IfStudentExistsRequest() {
        }
        
        public IfStudentExistsRequest(PointsStudentView.PointsService.IfStudentExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class IfStudentExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string studentNumber;
        
        public IfStudentExistsRequestBody() {
        }
        
        public IfStudentExistsRequestBody(string studentNumber) {
            this.studentNumber = studentNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IfStudentExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IfStudentExistsResponse", Namespace="http://pointservice.org/", Order=0)]
        public PointsStudentView.PointsService.IfStudentExistsResponseBody Body;
        
        public IfStudentExistsResponse() {
        }
        
        public IfStudentExistsResponse(PointsStudentView.PointsService.IfStudentExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://pointservice.org/")]
    public partial class IfStudentExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IfStudentExistsResult;
        
        public IfStudentExistsResponseBody() {
        }
        
        public IfStudentExistsResponseBody(bool IfStudentExistsResult) {
            this.IfStudentExistsResult = IfStudentExistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PointsServiceSoapChannel : PointsStudentView.PointsService.PointsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PointsServiceSoapClient : System.ServiceModel.ClientBase<PointsStudentView.PointsService.PointsServiceSoap>, PointsStudentView.PointsService.PointsServiceSoap {
        
        public PointsServiceSoapClient() {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PointsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PointsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.LoginResponse PointsStudentView.PointsService.PointsServiceSoap.Login(PointsStudentView.PointsService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string userId, string emailAddress) {
            PointsStudentView.PointsService.LoginRequest inValue = new PointsStudentView.PointsService.LoginRequest();
            inValue.Body = new PointsStudentView.PointsService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.emailAddress = emailAddress;
            PointsStudentView.PointsService.LoginResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.LoginResponse> PointsStudentView.PointsService.PointsServiceSoap.LoginAsync(PointsStudentView.PointsService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.LoginResponse> LoginAsync(string userId, string emailAddress) {
            PointsStudentView.PointsService.LoginRequest inValue = new PointsStudentView.PointsService.LoginRequest();
            inValue.Body = new PointsStudentView.PointsService.LoginRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.emailAddress = emailAddress;
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.GetStudentPointsResponse PointsStudentView.PointsService.PointsServiceSoap.GetStudentPoints(PointsStudentView.PointsService.GetStudentPointsRequest request) {
            return base.Channel.GetStudentPoints(request);
        }
        
        public PointsStudentView.PointsService.StudentPoints GetStudentPoints(string number) {
            PointsStudentView.PointsService.GetStudentPointsRequest inValue = new PointsStudentView.PointsService.GetStudentPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.GetStudentPointsRequestBody();
            inValue.Body.number = number;
            PointsStudentView.PointsService.GetStudentPointsResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).GetStudentPoints(inValue);
            return retVal.Body.GetStudentPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.GetStudentPointsResponse> PointsStudentView.PointsService.PointsServiceSoap.GetStudentPointsAsync(PointsStudentView.PointsService.GetStudentPointsRequest request) {
            return base.Channel.GetStudentPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.GetStudentPointsResponse> GetStudentPointsAsync(string number) {
            PointsStudentView.PointsService.GetStudentPointsRequest inValue = new PointsStudentView.PointsService.GetStudentPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.GetStudentPointsRequestBody();
            inValue.Body.number = number;
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).GetStudentPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.GetAllStudentPointsResponse PointsStudentView.PointsService.PointsServiceSoap.GetAllStudentPoints(PointsStudentView.PointsService.GetAllStudentPointsRequest request) {
            return base.Channel.GetAllStudentPoints(request);
        }
        
        public PointsStudentView.PointsService.StudentPoints[] GetAllStudentPoints() {
            PointsStudentView.PointsService.GetAllStudentPointsRequest inValue = new PointsStudentView.PointsService.GetAllStudentPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.GetAllStudentPointsRequestBody();
            PointsStudentView.PointsService.GetAllStudentPointsResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).GetAllStudentPoints(inValue);
            return retVal.Body.GetAllStudentPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.GetAllStudentPointsResponse> PointsStudentView.PointsService.PointsServiceSoap.GetAllStudentPointsAsync(PointsStudentView.PointsService.GetAllStudentPointsRequest request) {
            return base.Channel.GetAllStudentPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.GetAllStudentPointsResponse> GetAllStudentPointsAsync() {
            PointsStudentView.PointsService.GetAllStudentPointsRequest inValue = new PointsStudentView.PointsService.GetAllStudentPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.GetAllStudentPointsRequestBody();
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).GetAllStudentPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.UsePointsResponse PointsStudentView.PointsService.PointsServiceSoap.UsePoints(PointsStudentView.PointsService.UsePointsRequest request) {
            return base.Channel.UsePoints(request);
        }
        
        public bool UsePoints(string userRole, string studentNumber, double points) {
            PointsStudentView.PointsService.UsePointsRequest inValue = new PointsStudentView.PointsService.UsePointsRequest();
            inValue.Body = new PointsStudentView.PointsService.UsePointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            PointsStudentView.PointsService.UsePointsResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).UsePoints(inValue);
            return retVal.Body.UsePointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.UsePointsResponse> PointsStudentView.PointsService.PointsServiceSoap.UsePointsAsync(PointsStudentView.PointsService.UsePointsRequest request) {
            return base.Channel.UsePointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.UsePointsResponse> UsePointsAsync(string userRole, string studentNumber, double points) {
            PointsStudentView.PointsService.UsePointsRequest inValue = new PointsStudentView.PointsService.UsePointsRequest();
            inValue.Body = new PointsStudentView.PointsService.UsePointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).UsePointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.AddPointsResponse PointsStudentView.PointsService.PointsServiceSoap.AddPoints(PointsStudentView.PointsService.AddPointsRequest request) {
            return base.Channel.AddPoints(request);
        }
        
        public bool AddPoints(string userRole, string studentNumber, double points) {
            PointsStudentView.PointsService.AddPointsRequest inValue = new PointsStudentView.PointsService.AddPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.AddPointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            PointsStudentView.PointsService.AddPointsResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).AddPoints(inValue);
            return retVal.Body.AddPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.AddPointsResponse> PointsStudentView.PointsService.PointsServiceSoap.AddPointsAsync(PointsStudentView.PointsService.AddPointsRequest request) {
            return base.Channel.AddPointsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.AddPointsResponse> AddPointsAsync(string userRole, string studentNumber, double points) {
            PointsStudentView.PointsService.AddPointsRequest inValue = new PointsStudentView.PointsService.AddPointsRequest();
            inValue.Body = new PointsStudentView.PointsService.AddPointsRequestBody();
            inValue.Body.userRole = userRole;
            inValue.Body.studentNumber = studentNumber;
            inValue.Body.points = points;
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).AddPointsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PointsStudentView.PointsService.IfStudentExistsResponse PointsStudentView.PointsService.PointsServiceSoap.IfStudentExists(PointsStudentView.PointsService.IfStudentExistsRequest request) {
            return base.Channel.IfStudentExists(request);
        }
        
        public bool IfStudentExists(string studentNumber) {
            PointsStudentView.PointsService.IfStudentExistsRequest inValue = new PointsStudentView.PointsService.IfStudentExistsRequest();
            inValue.Body = new PointsStudentView.PointsService.IfStudentExistsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            PointsStudentView.PointsService.IfStudentExistsResponse retVal = ((PointsStudentView.PointsService.PointsServiceSoap)(this)).IfStudentExists(inValue);
            return retVal.Body.IfStudentExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PointsStudentView.PointsService.IfStudentExistsResponse> PointsStudentView.PointsService.PointsServiceSoap.IfStudentExistsAsync(PointsStudentView.PointsService.IfStudentExistsRequest request) {
            return base.Channel.IfStudentExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PointsStudentView.PointsService.IfStudentExistsResponse> IfStudentExistsAsync(string studentNumber) {
            PointsStudentView.PointsService.IfStudentExistsRequest inValue = new PointsStudentView.PointsService.IfStudentExistsRequest();
            inValue.Body = new PointsStudentView.PointsService.IfStudentExistsRequestBody();
            inValue.Body.studentNumber = studentNumber;
            return ((PointsStudentView.PointsService.PointsServiceSoap)(this)).IfStudentExistsAsync(inValue);
        }
    }
}
